# Generated by Django 6.0.3 on 2026-03-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0002_alter_model_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={},
        ),
    ]
