image: centos:centos7

before_script:
  - yum install -y -t https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - yum -y -t install python34 python34-pip python34-devel unzip mysql-devel gcc
  - pip3 install virtualenv --upgrade
  - virtualenv -p python3 /tmp/.virtualenv
  - source /tmp/.virtualenv/bin/activate
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage

test_and_coverage:
  stage: test
  script:
    - pushd sm
    - python manage.py collectstatic --noinput
    - coverage run --source . manage.py test -v3
    - coverage report --fail-under=70
    - coverage html
    - popd
  artifacts:
    paths:
      - sm/htmlcov/

pages:
  stage: deploy
  dependencies:
    - test_and_coverage
  script:
    - mv sm/htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
