prepare:
  script:
    - source .virtualenv/bin/activate
    - pushd sm
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - popd

coverage:
  script:
    - source .virtualenv/bin/activate
    - pushd sm
    - coverage run manage.py test -v3
    - popd
