prepare:
  script:
    - yum install -y -t https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - yum -y -t install python34 python34-pip
    - pip3 install virtualenv --upgrade
    - virtualenv -p python3 /tmp/.virtualenv
    - source /tmp/.virtualenv/bin/activate
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install coverage
    - pushd sm
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - popd

coverage:
  script:
    - source /tmp/.virtualenv/bin/activate
    - pushd sm
    - coverage run manage.py test -v3
    - popd
