language: python
python:
  - "3.5"
env:
  matrix:
   - DJANGO="Django<1.11"
branches:
    only:
        - master
# command to install dependencies
install:
  - virtualenv -p python3 .virtualenv:
  - source .virtualenv/bin/activate
  - pip install -r requirements.txt
  - pip install "$DJANGO"
  - pip install python-coveralls
  - pip install coverage
before_script:
  - source .virtualenv/bin/activate
  - pushd sm
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - popd
# command to run tests
script:
  - source .virtualenv/bin/activate
  - coverage run manage.py test -v3
