# Generated by Django 2.0.1 on 2018-02-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterpackagetype', '0001_initial'),
        ('clusterpackage', '0002_auto_20180215_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='package_type',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.PROTECT, related_name='clusterpackage_set', related_query_name='clusterpackage_set', to='clusterpackagetype.Model'),
            preserve_default=False,
        ),
    ]
