# Generated by Django 6.0.3 on 2026-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0013_alter_model_options"),
        ("clusterpackage", "0005_alter_model_id"),
        (
            "clusterpackagetype",
            "0003_alter_model_options_alter_model_unique_together_and_more",
        ),
        ("status", "0003_alter_model_options"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",  # noqa # flake8: noqa # NOQA # pragma: no cover
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("cluster", "name"), name="unique_sm_clusterpackage_cluster_name"
            ),
        ),
    ]
