# Generated by Django 6.0.3 on 2026-03-23 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cluster", "0015_model_unique_sm_cluster_name_group"),
        (
            "clusterpackage",
            "0007_alter_model_cluster_alter_model_package_type_and_more",
        ),
        ("clusterpackagetype", "0005_historicalmodel_group_model_group_and_more"),
        ("status", "0006_alter_model_name"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",  # noqa: E501
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodel",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="group",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clusterpackages",
                to="auth.group",
            ),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("cluster", "name", "group"),
                name="unique_sm_clusterpackage_cluster_name_group",
            ),
        ),
    ]
