# Generated by Django 6.1 on 2026-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cluster', '0015_model_unique_sm_cluster_name_group'),
        ('clusterpackage', '0008_historicalmodel_group_model_group_and_more'),
        ('clusterpackagetype', '0005_historicalmodel_group_model_group_and_more'),
        ('status', '0006_alter_model_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='model',
            name='unique_sm_clusterpackage_cluster_name',
        ),
        migrations.RemoveConstraint(
            model_name='model',
            name='unique_sm_clusterpackage_cluster_name_group',
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('cluster', 'name', 'status', 'package_type', 'group'), name='unique_sm_clusterpackage_cluster_name_status_package_type_group'),
        ),
    ]
