# Generated by Django 1.11 on 2017-09-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("version", models.CharField(max_length=45)),
                (
                    "vendor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clustersoftware_set",
                        related_query_name="clustersoftware",
                        to="vendor.Model",
                    ),
                ),
            ],
            options={
                "db_table": "sm_clustersoftware",
                "managed": True,
            },
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("vendor", "version")},
        ),
        migrations.AlterField(
            model_name="model",
            name="vendor",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clustersoftware_set",
                related_query_name="clustersoftware",
                to="vendor.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="version",
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
