# Generated by Django 1.11 on 2017-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0001_initial"),
        ("clustersoftware", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="version",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("vendor", "name", "version")},
        ),
    ]
