# Generated by Django 1.11 on 2017-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clustersoftware", "0002_auto_20170908_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="version",
            field=models.CharField(default="", max_length=45),
        ),
    ]
