# Generated by Django 1.11 on 2017-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clustersoftware", "0003_auto_20170908_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="version",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
    ]
