# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clustersoftware', '0004_auto_20170908_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(default=53, on_delete=django.db.models.deletion.CASCADE, related_name='clustersoftware_set', related_query_name='clustersoftware', to='vendor.Model'),
            preserve_default=False,
        ),
    ]
