# Generated by Django 1.11.7 on 2017-12-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clustersoftware", "0005_auto_20170908_1029"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"managed": True, "ordering": ["vendor", "name", "version"]},
        ),
    ]
