# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clustersoftware', '0006_auto_20171213_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clustersoftware_set', related_query_name='clustersoftware', to='vendor.Model'),
        ),
    ]
