# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustersoftware', '0007_auto_20171214_0932'),
        ('clustersoftware', '0007_auto_20180103_1241'),
    ]

    operations = [
    ]
