# Generated by Django 6.0.3 on 2026-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clustersoftware", "0009_alter_model_id"),
        ("vendor", "0006_alter_model_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("vendor", "name", "version"),
                name="unique_sm_clustersoftware_vendor_name_version",
            ),
        ),
    ]
