# Generated by Django 6.1 on 2026-08-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clustersoftware", "0014_model_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("vendor", "0011_model_tags"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", True)),
                fields=("vendor", "name", "version"),
                name="unique_sm_clustersoftware_global_vendor_name_version",
            ),
        ),
    ]
