apiVersion: v1
kind: ConfigMap
metadata:
  name: sm-config
  namespace: localghost
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "sm.localghost.com"
  EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
  THEME_CONTACT_EMAIL: "oliver@linux-kernel.at"
  THEME_GITHUB_URL: "https://github.com/ofalk/sm"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sm-caddy-config
  namespace: localghost
data:
  Caddyfile: |
    :8080 {
        handle /static/* {
            uri strip_prefix /static
            root * /app/sm/static
            file_server
        }
        handle {
            reverse_proxy localhost:8000 {
                header_up X-Forwarded-Proto {header.X-Forwarded-Proto}
            }
        }
    }
