# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patchtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=45)),
                ('delivery_date', models.DateTimeField(auto_now=True)),
                ('install_date', models.DateTimeField(auto_now=True)),
                ('documentation_url', models.URLField(max_length=2083)),
                ('memory_in_mb', models.IntegerField(blank=True, null=True)),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_hostname', models.CharField(blank=True, max_length=45, null=True)),
                ('delivery_note_id', models.CharField(blank=True, max_length=45, null=True)),
                ('serial_nr', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('patchtime', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sm.Patchtime')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sm.Status'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('hostname', 'status')]),
        ),
    ]
