# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'country')]),
        ),
    ]
