# Generated by Django 6.0.3 on 2026-03-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sm", "0002_invitation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invitation",
            name="sm_invitation_email_group_unique",
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("email", "group")},
        ),
    ]
