# Generated by Django 6.0.3 on 2026-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sm", "0004_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiry timestamp. Expired keys are rejected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, help_text="When the key was revoked or rotated.", null=True
            ),
        ),
    ]
