# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0004_auto_20170627_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='version',
            field=models.CharField(max_length=45),
        ),
    ]
