# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0005_auto_20170627_1220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatingsystem',
            unique_together=set([('vendor', 'version')]),
        ),
    ]
