# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0008_auto_20170817_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sm.Location'),
            preserve_default=False,
        ),
    ]
