# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0009_server_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='install_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
