# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0012_auto_20170830_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sm.Location'),
        ),
    ]
