# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0014_auto_20170831_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='operatingsystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sm.Operatingsystem'),
        ),
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sm.Location'),
        ),
    ]
