# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0015_auto_20170831_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='operatingsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sm.Operatingsystem'),
        ),
    ]
