# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0016_auto_20170901_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sm.Vendor')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='server',
            name='servermodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sm.Servermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='servermodel',
            unique_together=set([('vendor', 'name')]),
        ),
    ]
