# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operatingsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
            options={
                'db_table': 'sm_operatingsystem',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='operatingsystem',
            unique_together=set([('vendor', 'version')]),
        ),
    ]
