# Generated by Django 1.11.9 on 2018-01-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operatingsystem", "0002_auto_20171213_0937"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="model",
            name="vendor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operatingsystem_set",
                related_query_name="operatingsystem",
                to="vendor.Model",
            ),
        ),
    ]
