# Generated by Django 6.0.3 on 2026-08-15 10:43

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patchtime", "0005_historicalmodel_group_model_group_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
