# Generated by Django 6.1 on 2026-08-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("patchtime", "0006_model_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", True)),
                fields=("name",),
                name="unique_sm_patchtime_global_name",
            ),
        ),
    ]
