# Generated by Django 6.0.3 on 2026-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_alter_model_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_sm_location_name_country"
            ),
        ),
    ]
