# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vendor.Model')),
            ],
            options={
                'managed': True,
                'db_table': 'sm_servermodel',
            },
        ),
        migrations.AlterUniqueTogether(
            name='servermodel',
            unique_together=set([('vendor', 'name')]),
        ),
    ]
