# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='servermodel_set', related_query_name='servermodel', to='vendor.Model')),
            ],
            options={
                'db_table': 'sm_servermodel',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('vendor', 'name')]),
        ),
    ]
