# Generated by Django 1.11.8 on 2017-12-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servermodel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="vendor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servermodel_set",
                related_query_name="servermodel",
                to="vendor.Model",
            ),
        ),
    ]
