# Generated by Django 6.0.3 on 2026-03-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("servermodel", "0006_historicalmodel"),
        ("vendor", "0010_historicalmodel_group_model_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodel",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="group",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servermodels",
                to="auth.group",
            ),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("vendor", "name", "group"),
                name="unique_sm_servermodel_vendor_name_group",
            ),
        ),
    ]
