# Generated by Django 6.0.3 on 2026-08-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servermodel", "0007_historicalmodel_group_model_group_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="model",
            name="unique_sm_servermodel_vendor_name",
        ),
    ]
