# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name=b'Domain name'),
        ),
    ]
