# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20171214_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='check_whois',
            field=models.BooleanField(default=True),
        ),
    ]
