# Generated by Django 1.11.8 on 2017-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_model_check_whois"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="admin_email",
            field=models.CharField(
                blank=True,
                max_length=45,
                null=True,
                verbose_name=b"Whois admin email to check",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="tech_email",
            field=models.CharField(
                blank=True,
                max_length=45,
                null=True,
                verbose_name=b"Whois tech email to check",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="check_whois",
            field=models.BooleanField(
                default=True, verbose_name=b"Check whois via monitoring?"
            ),
        ),
    ]
