# Generated by Django 1.11.8 on 2017-12-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0004_auto_20171214_0939"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="admin_email",
        ),
        migrations.RemoveField(
            model_name="model",
            name="check_whois",
        ),
        migrations.RemoveField(
            model_name="model",
            name="tech_email",
        ),
    ]
