# Generated by Django 2.0.1 on 2018-01-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20171218_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Domain name'),
        ),
    ]
