# Generated by Django 6.0.3 on 2026-03-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("domain", "0010_historicalmodel_group_model_group"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("name", "group"), name="unique_sm_domain_name_group"
            ),
        ),
    ]
