# Generated by Django 6.0.3 on 2026-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0011_model_unique_sm_domain_name_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmodel",
            name="name",
            field=models.CharField(max_length=45, verbose_name="Domain name"),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=45, verbose_name="Domain name"),
        ),
    ]
