# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operatingsystem', '0001_initial'),
        ('cluster', '0002_auto_20170908_0855'),
        ('domain', '0001_initial'),
        ('servermodel', '0001_initial'),
        ('location', '0001_initial'),
        ('status', '0001_initial'),
        ('patchtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=45)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('install_date', models.DateField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('documentation_url', models.URLField(blank=True, max_length=2083, null=True)),
                ('memory_in_mb', models.IntegerField(blank=True, null=True)),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_hostname', models.CharField(blank=True, max_length=45, null=True)),
                ('delivery_note_id', models.CharField(blank=True, max_length=45, null=True)),
                ('serial_nr', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cluster.Model')),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='domain.Model')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Model')),
                ('operatingsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operatingsystem.Model')),
                ('patchtime', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patchtime.Model')),
                ('servermodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servermodel.Model')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='status.Model')),
            ],
            options={
                'managed': True,
                'db_table': 'sm_server',
            },
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('hostname', 'status')]),
        ),
    ]
