# Generated by Django 1.11 on 2017-09-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_auto_20170908_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="cluster.Model",
            ),
        ),
    ]
