# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170908_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='Model',
        ),
    ]
