# Generated by Django 1.11.7 on 2017-12-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_auto_20171213_0650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="domain",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="domain.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="location.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="operatingsystem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="operatingsystem.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="patchtime",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_set",
                related_query_name="server",
                to="patchtime.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="servermodel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="servermodel.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="status.Model",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=set(),
        ),
    ]
