# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('server', '0005_auto_20171213_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='domain.Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='operatingsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operatingsystem.Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='patchtime',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='patchtime.Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='servermodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servermodel.Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='status.Model'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('hostname', 'status')]),
        ),
    ]
