# Generated by Django 2.0.1 on 2018-01-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_auto_20180104_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="location.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="patchtime",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="patchtime.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="servermodel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="servermodel.Model",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="server_set",
                related_query_name="server",
                to="status.Model",
            ),
        ),
    ]
