# Generated by Django 6.0.3 on 2026-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_auto_20180118_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
