# Generated by Django 6.0.3 on 2026-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0013_alter_model_options"),
        ("domain", "0008_alter_model_options"),
        ("location", "0003_alter_model_options_alter_model_unique_together_and_more"),
        (
            "operatingsystem",
            "0006_alter_model_options_alter_model_unique_together_and_more",
        ),
        ("patchtime", "0003_alter_model_options"),
        ("server", "0010_alter_model_id"),
        (
            "servermodel",
            "0005_alter_model_options_alter_model_unique_together_and_more",
        ),
        ("status", "0003_alter_model_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("hostname", "status"), name="unique_sm_server_hostname_status"
            ),
        ),
    ]
