# Generated by Django 6.0.3 on 2026-03-10 07:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0014_historicalmodel"),
        ("domain", "0008_alter_model_options"),
        ("location", "0003_alter_model_options_alter_model_unique_together_and_more"),
        ("operatingsystem", "0007_historicalmodel"),
        ("patchtime", "0003_alter_model_options"),
        ("server", "0011_alter_model_options_alter_model_unique_together_and_more"),
        (
            "servermodel",
            "0005_alter_model_options_alter_model_unique_together_and_more",
        ),
        ("status", "0003_alter_model_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalModel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("hostname", models.CharField(max_length=45)),
                ("delivery_date", models.DateField(default=django.utils.timezone.now)),
                ("install_date", models.DateField(default=django.utils.timezone.now)),
                ("last_update", models.DateTimeField(blank=True, editable=False)),
                (
                    "documentation_url",
                    models.URLField(blank=True, max_length=2083, null=True),
                ),
                ("memory_in_mb", models.IntegerField(blank=True, null=True)),
                ("monitoring_from_puppet", models.BooleanField(default=False)),
                ("primary_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("management_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "management_hostname",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "delivery_note_id",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("serial_nr", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="server",
                        to="cluster.model",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="domain.model",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="server",
                        to="location.model",
                    ),
                ),
                (
                    "operatingsystem",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="server",
                        to="operatingsystem.model",
                    ),
                ),
                (
                    "patchtime",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="server",
                        to="patchtime.model",
                    ),
                ),
                (
                    "servermodel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="server",
                        to="servermodel.model",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="server",
                        to="status.model",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical model",
                "verbose_name_plural": "historical models",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
