# Generated by Django 6.0.3 on 2026-03-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cluster", "0015_model_unique_sm_cluster_name_group"),
        ("domain", "0011_model_unique_sm_domain_name_group"),
        ("location", "0005_historicalmodel_group_model_group"),
        (
            "operatingsystem",
            "0008_remove_model_unique_sm_operatingsystem_vendor_version_and_more",
        ),
        ("patchtime", "0004_historicalmodel"),
        ("server", "0013_historicalmodel_group_model_group"),
        ("servermodel", "0006_historicalmodel"),
        ("status", "0004_historicalmodel"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("hostname", "status", "group"),
                name="unique_sm_server_hostname_status_group",
            ),
        ),
    ]
