# Generated by Django 6.0.3 on 2026-08-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0014_model_unique_sm_server_hostname_status_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="model",
            name="unique_sm_server_hostname_status",
        ),
    ]
