# Generated by Django 6.0.3 on 2026-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0016_model_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodel",
            name="application",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalmodel",
            name="rack",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="application",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="rack",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
