# Generated by Django 6.0.3 on 2026-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0017_historicalmodel_application_historicalmodel_rack_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmodel",
            name="monitoring_from_puppet",
            field=models.BooleanField(default=False, verbose_name="Monitoring"),
        ),
        migrations.AlterField(
            model_name="model",
            name="monitoring_from_puppet",
            field=models.BooleanField(default=False, verbose_name="Monitoring"),
        ),
    ]
