# Generated by Django 6.0.3 on 2026-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0018_alter_historicalmodel_monitoring_from_puppet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodel",
            name="decommission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="decommission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
