# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_auto_20170908_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='clustersoftware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_set', related_query_name='cluster', to='clustersoftware.Model'),
        ),
    ]
