# Generated by Django 1.11.7 on 2017-12-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0004_auto_20170915_0850"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"managed": True, "ordering": ["name"]},
        ),
    ]
