# Generated by Django 1.11.8 on 2017-12-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0005_auto_20171213_0937"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="model",
            name="clustersoftware",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cluster_set",
                related_query_name="cluster",
                to="clustersoftware.Model",
            ),
        ),
    ]
