# Generated by Django 1.11.7 on 2017-11-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0005_model_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="group",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.Group",
            ),
        ),
    ]
