# Generated by Django 1.11.9 on 2018-01-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0005_auto_20171213_0937"),
        ("cluster", "0007_auto_20171121_1432"),
    ]

    operations = []
