# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_merge_20180103_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='model',
            name='clustersoftware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cluster_set', related_query_name='cluster', to='clustersoftware.Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
