# Generated by Django 1.11.9 on 2018-01-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0009_auto_20180103_1241"),
        ("cluster", "0006_auto_20171214_0932"),
    ]

    operations = []
