# Generated by Django 2.0.1 on 2018-01-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0010_merge_20180103_1328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="group",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.Group",
            ),
        ),
    ]
