# Generated by Django 6.0.3 on 2026-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0015_model_unique_sm_cluster_name_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmodel",
            name="name",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=45),
        ),
    ]
